### ISSUE TITLE
Fix systemd target

### ISSUE THREAD

**Issue by friday** [friday/Ulauncher-Revived#49]
WantedBy=graphical.target should be WantedBy=default.target because it's a user unit, not a system unit. See https://unix.stackexchange.com/a/598055/119669

Already fixed in 0e9b51fe6b6f27b8324227bbfc45407b4ad935f2, but adding issue to keep track of what's been done.

**Comment by troycurtisjr** [comment]
Is this the correct target though? Doesn't this also get executed by non-graphical sessions? It does seem that graphical.target is the system one, but perhaps the more appropriate target is actually graphical-session.target https://www.freedesktop.org/software/systemd/man/systemd.special.html#graphical-session.target ?

**Comment by friday** [comment]
I think you are right @troycurtisjr. I will reopen and check back with this later.

**Comment by friday** [comment]
graphical-session.target worked :+1: Thanks for doing the homework for me 🙏
